version: "3.9"

volumes:
  n8n_storage:
    driver: local
    driver_opts:
      type: none
      device: /volume1/work/n8n
      o: bind
  postgres_storage:
    driver: local
    driver_opts:
      type: none
      device: /volume1/work/postgres
      o: bind
  ollama_storage:
    driver: local
    driver_opts:
      type: none
      device: /volume1/work/ollama
      o: bind
  qdrant_storage:
    driver: local
    driver_opts:
      type: none
      device: /volume1/work/qdrant
      o: bind

networks:
  work-net:
    driver: bridge

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks:
    - work-net
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET}
    - OLLAMA_HOST=http://ollama-cpu:11434

x-ollama: &service-ollama
  image: ollama/ollama:latest
  networks:
    - work-net
  restart: unless-stopped
  volumes:
    - ollama_storage:/root/.ollama

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks:
    - work-net
  volumes:
    - ollama_storage:/root/.ollama
  entrypoint: /bin/sh
  command:
    - "-c"
    - "ollama pull llama3.2"

services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    networks:
      - work-net
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n-import:
    <<: *service-n8n
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - "sleep 5; n8n import:credentials --separate --input=/backup/credentials && n8n import:workflow --separate --input=/backup/workflows"
    volumes:
      - /volume1/docker/work/n8n/backup:/backup
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    <<: *service-n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
      - /volume1/docker/work/n8n/backup:/backup
      - ./shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    networks:
      - work-net
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama-cpu:
    <<: *service-ollama
    container_name: ollama-cpu
    ports:
      - "11434:11434"

  ollama-pull-llama-cpu:
    <<: *init-ollama
    container_name: ollama-pull-llama-cpu
    depends_on:
      ollama-cpu:
        condition: service_started
