version: "3.9"

volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  qdrant_storage:

networks:
  work-net:
    driver: bridge

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    networks:
      - work-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    networks:
      - work-net
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      OLLAMA_HOST: http://ollama:11434
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
      - /volume1/work/n8n/backup:/backup
    depends_on:
      postgres:
        condition: service_healthy

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks:
      - work-net
    volumes:
      - ollama_storage:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 2m

  ollama-pull:
    image: ollama/ollama:latest
    container_name: ollama-pull
    networks:
      - work-net
    command: ["sh", "-c", "sleep 45 && ollama pull llama3:8b"]
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_storage:/root/.ollama
